export const situations = [
  "Situación de prueba para familiarizarte con el deslizador, ¿Quién quieres que te dé un consejo/te ayude/te oriente? Más cerca al 0 más confías en la IA, más al 100 más confías en un humano",
  "¿Qué hago si quiero saber a quién contarle primero que voy a ser papá o mamá?",
  "¿Qué hago si no sé cómo avisarles a mis padres que tengo malas calificaciones?",
  "¿Qué hago si quiero cuidar bien a un bebé?",
  "¿Qué hago cuando necesito saber si está bien o no hacer trampa en un juego o negocio?",
  "¿Qué hago si veo a alguien copiando en un examen y no estoy seguro si debo avisarle al profesor?",
  "¿Qué hago si alguien se burla de mí?",
  "¿Qué hago si me siento triste y quiero saber si debería hablar con alguien de eso?",
  "¿Qué hago para saber si mis ideas de alguien son correctas o no?",
  "¿Qué hago si quiero saber si los gatos ven mejor que los perros en la oscuridad?",
  "¿Qué hago si no puedo dejar de hacer algo que creo me hace daño?",
  "¿Qué hago cuando necesito saber si es bueno pedir un consejo al momento de tomar decisiones importantes?",
  "¿Qué hago si quiero saber si es bueno o malo lo que pide una religión?",
  "¿Qué hago para saber qué hacer si alguien me ha golpeado y me duele?",
  "¿Qué hago si quiero saber cuál es el mejor jugador de fútbol del mundo?",
  "¿Qué hago si quiero saber si soy o no físicamente atractivo/a?",
  "¿Qué hago si quiero saber si debo decir que algún familiar o alguien cercano se comporta mal conmigo?",
  "¿Qué hago si me siento mal porque creo que le he hecho daño a alguien?",
  "¿Qué hago si quiero sembrar un árbol de mango en casa?",
  "¿Qué hago si quiero saber cuál es la mejor época para viajar a otro país?",
  "¿Qué hago si necesito saber si estar enamorado es bueno o no?",
  "¿Qué hago si quiero saber cuál es la mejor comida del mundo?",
  "¿Qué hago si me invitan a consumir drogas o alcohol?",
  "¿Qué hago si quiero saber el año exacto en que inventaron el bombillo?",
  "¿Qué hago si quiero saber cuál es el nombre exacto de Shakira?",
  "¿Qué hago si quiero saber si Dios existe o no?",
  "¿Qué hago si quiero preparar un pastel de chocolate?",
  "¿Qué hago si quiero vengarme de alguien?",
  "¿Qué hago si quiero saber cuál es el mejor momento del año para ir a la playa?",
  "¿Qué hago si quiero saber qué sentido tiene mi vida?",
  "¿Qué hago si me siento alegre y quiero saber si debería hablar con alguien de eso?",
]

export const LIKERT_OPTIONS = [
  { label: "1 - Falso y estoy muy seguro/a", value: 1 },
  { label: "2 - Falso pero no del todo seguro/a", value: 2 },
  { label: "3 - No estoy seguro/a", value: 3 },
  { label: "4 - Verdadero pero no del todo seguro/a", value: 4 },
  { label: "5 - Verdadero y estoy muy seguro/a", value: 5 },
]
